language: php
php:
    - 5.6
    - 7.0
    - hhvm

services:
    - docker
#env:
#    matrix:
#    - DOCKERRUN="docker run -d -p 5984:5984 klaemo/couchdb:1.6.1"
#    - DOCKERRUN="docker run -it klaemo/couchdb:2.0-dev --admin=foo:bar"

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

sudo: 
  required

before_install:
#    - git clone https://github.com/klaemo/docker-couchdb.git
#    - cd docker-couchdb
#    - mkdir couchdb && cd ./couchdb
#    - $DOCKERRUN
    - docker run -d -it -p 5984:5984 klaemo/couchdb:2.0-dev --with-admin-party-please --with-haproxy
    - sleep 5
#    - cd ../../

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
    - curl http://localhost:5984
    - php ./tests/_config/_setupEnvironment.php
    - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --configuration ./phpunit.xml  --testsuite Ordered

    
after_success:
- php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
