language: php
php:
    - 5.6
    - 7.0
    - hhvm

services:
    - docker
    
install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

sudo: 
  required

before_install:
    - docker run -d -it -p 5984:5984 klaemo/couchdb:1.6.1
    - sleep 5

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
    - curl http://localhost:5984
    - php ./tests/_config/_setupEnvironment.php
    - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --configuration ./phpunit.xml  --testsuite Ordered

    
after_success:
- php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
