language: php
php:
    - '5.6'
    - '7.0'
install:
    - composer install
    - composer dump-autoload

before_script:
  - php ./tests/_config/_setupEnvironment.php
 
script:
    - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --configuration ./phpunit.xml  --testsuite Ordered

    
services:
    - couchdb
    
after_success:
- php vendor/bin/coveralls -v


notifications:
  email: false